name: Build Assyst tags

on: push

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkoout repository
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
      - name: Minify and put tag files
        id: build
        run: |
          npm ci
          npm run build
          for tag in out/*.js; do echo "{js:const args='{args}';{ignore:$(<$tag)}}">$tag; done

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: out/

  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
